### ISSUE TITLE
Make the bot rename to sender's name and use their picture

### ISSUE THREAD

**Issue by hmlendea** [TediCross/TediCross#173] opened 2021-01-04 18:05 UTC
Hello,

I also gave https://github.com/miscord/miscord which is a somewhat similar bot to this one except that it bridges Discord with Facebook (not Telegram).

And it is able to rename the bot on Discord to the sender's name from Facebook and also use their profile picture in the message.

Could it be possible to do the same with TediCross? At least one of those, would be greatly appreciated

**Comment by hmlendea** [comment] 2021-01-04 20:47
The same is done in DiscordSRV for Minecraft

Apparently they use Web Hooks to achieve this

**Comment by trgwii** [comment] 2021-01-05 09:10
Unfortunately the last time we tested this, using webhooks prevented the editing functionality of this bot, so we probably won't do this.

**Comment by Suppen** [comment] 2021-01-05 18:01
Closing as duplicate of #172

**Closed by Suppen** 2021-01-05 18:01 UTC
