### ISSUE TITLE
Custom Emoji should not be sent to Telegram.

### ISSUE THREAD

**Issue by barning** [TediCross/TediCross#121] opened 2019-09-25 12:06 UTC
If Discord, or Discord-Nitro User use Custom Emoji, they will be sent to Telegram. This should be switched off to avoid annoying Telegram members.

**Comment by tux93** [comment] 2019-12-01 14:40
I rather think they should be sent as images like it is with Telegram Stickers instead of sending their ID: `<:wow:447942202828783637>`

**Comment by tux93** [comment] 2019-12-01 14:44
Just saw the Wontfix on #44 
In that case an option to disable them altogether would be nice to have, yes

**Comment by Suppen** [comment] 2020-01-25 22:15
It should be simple enough to make them disappear, or replace them with just their code (`:wow` in the mentioned case). but I'm unable to test this due to lack of Discord Nitro

**Comment by barning** [comment] 2020-01-26 10:06
Custom emojis are not limited to Nitro. Is there a database with official Emoji, so :wow: will be filtered out until there is a Wow-Emoji?

**Comment by Suppen** [comment] 2020-01-26 21:51
The emojis defined in unicode will go through the bot as unicode emojis, not as their text representation. ":smile:" will for example go through as the actual smile emoji, not as ":smile:"
Custom emojis are not defined in unicode. It should therefore be safe to filter on ":something:", and no database over official emojis is needed

**Comment by Suppen** [comment] 2020-01-26 21:55
I'm not very familiar with custom emojis. Is it possible to define custom emojis with the same names as the ones defined in unicode?

**Comment by vico93** [comment] 2020-09-16 12:25
About this issue: Discord servers (guilds) have 50 slots free for custom emojis, so its not a nitro-only feature (but nitro users have unlimited and personal emojis).

Particulary i dont care about nitro at all, but forwarding the guild/server emojis as images or stickers could be good, or adding an option to not relay/filter out the ugly code at all. Or even allowing a list to textual emoji (like the old ones `:-)` `:-(` ) to replace the ugly emoji code would be sufficient.

**Comment by vico93** [comment] 2020-09-16 12:26
> I'm not very familiar with custom emojis. Is it possible to define custom emojis with the same names as the ones defined in unicode?

No, if you add an emoji with a duplicate name (not only for a standard unicode but also for other custom emojis) it will append a `~x` (x being a number) at the end of the shortcode. Happens also with emojis with same shortcode across servers with same owner.

**Comment by Lulalaby** [comment] 2023-03-09 09:15
# Issue Check

- Can this issue be closed
- Does this issue still needs attention

**Comment by Lulalaby** [comment] 2023-03-24 06:29
## Automatic issue close

Your issue was automatically closed.
We currently clean-up the issues to keep track of confirmed bugs.
If this bug is still valid, please open a [new issue](https://github.com/TediCross/TediCross/issues/new).

See https://github.com/TediCross/TediCross/issues/256 for more details.

**Closed by Lulalaby** 2023-03-24 06:29 UTC
Labels: bug, checking, act-check
